# Generated by Django 6.0.5 on 2026-06-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('t1_review', 'T1 Project Review'), ('t2_review', 'T2 Project Review'), ('t3_review', 'T3/Fraud Project Review'), ('printer', 'Project Printer'), ('fulfillment', 'Fulfill shop orders'), ('statistics', 'View statistics')],
            },
        ),
    ]
