# Generated by Django 6.0.5 on 2026-06-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0008_project_locked_alter_ship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
