# Generated by Django 6.0.5 on 2026-06-06 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0009_project_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': [('t1_review', 'T1 Project Review'), ('t2_review', 'T2 Project Review'), ('t3_review', 'T3/Fraud Project Review'), ('printer', 'Project Printer'), ('fulfillment', 'Fulfill shop orders'), ('organizer', 'Access to everything')], 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AddField(
            model_name='item',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
