# Generated by Django 6.0.5 on 2026-06-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0010_alter_permissions_options_item_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imageUrl',
            field=models.CharField(default='https://example.com', max_length=250),
        ),
    ]
