# Generated by Django 6.0.5 on 2026-06-13 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0014_remove_order_fulfilled_order_address_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True)),
                ('printed', models.BooleanField(default=False)),
                ('image_url', models.CharField(blank=True, max_length=200)),
                ('feedback', models.CharField(blank=True, max_length=100)),
                ('internal_notes', models.CharField(blank=True, max_length=100)),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prints', to=settings.AUTH_USER_MODEL)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prints', to='layered_site.ship')),
            ],
        ),
        migrations.CreateModel(
            name='T1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.CharField(max_length=100)),
                ('internal_notes', models.CharField(max_length=100)),
                ('approved', models.BooleanField()),
                ('print', models.BooleanField(default=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t1_reviews', to=settings.AUTH_USER_MODEL)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t1_reviews', to='layered_site.ship')),
            ],
        ),
        migrations.CreateModel(
            name='T2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.CharField(max_length=100)),
                ('justification', models.CharField(max_length=400)),
                ('approved', models.BooleanField()),
                ('deductions', models.IntegerField(default=0)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t2_reviews', to=settings.AUTH_USER_MODEL)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t2_reviews', to='layered_site.ship')),
            ],
        ),
    ]
