# Generated by Django 6.0.5 on 2026-06-13 23:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0016_alter_item_imageurl_alter_print_image_url_journal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='print',
            name='printed',
        ),
        migrations.RemoveField(
            model_name='t2',
            name='approved',
        ),
        migrations.AddField(
            model_name='print',
            name='claimed_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='print',
            name='decision',
            field=models.CharField(choices=[('T1', 'Returned to T1 Review'), ('R', 'Rejected'), ('A', 'Approve')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='print',
            name='unclaimed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t2',
            name='decision',
            field=models.CharField(choices=[('T1', 'Returned to T1 Review'), ('P', 'Returned to Printers'), ('A', 'Approved')], default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='print',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='T3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(choices=[('T1', 'Returned to T1 Review'), ('P', 'Returned to Printers'), ('T2', 'Returned to T2 Review'), ('A', 'Approved')], default='A', max_length=2)),
                ('payout_hours', models.IntegerField()),
                ('airtable_hours', models.IntegerField()),
                ('internal_comments', models.CharField(blank=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='t3_reviews', to=settings.AUTH_USER_MODEL)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t3_reviews', to='layered_site.ship')),
            ],
        ),
    ]
