# Generated by Django 6.0.5 on 2026-06-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0017_remove_print_printed_remove_t2_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='status',
            field=models.CharField(choices=[('R', 'Rejected'), ('T1', 'Under T1 Review'), ('PQ', 'In print queue'), ('BP', 'Being printed'), ('T2', 'Under T2 Review'), ('T3', 'Under fraud review'), ('F', 'Finalized')], default='T1', max_length=2),
        ),
    ]
