# Generated by Django 6.0.5 on 2026-06-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0018_alter_ship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t3',
            name='airtable_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='t3',
            name='payout_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
