# Generated by Django 6.0.5 on 2026-06-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0019_alter_t3_airtable_hours_alter_t3_payout_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t3',
            old_name='internal_comments',
            new_name='internal_notes',
        ),
    ]
