# Generated by Django 6.0.5 on 2026-06-24 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0027_remove_ship_submitted_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfiller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_fulfilled', to=settings.AUTH_USER_MODEL),
        ),
    ]
