# Generated by Django 6.0.5 on 2026-07-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0031_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='editor_model_url',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
