# Generated by Django 6.0.5 on 2026-07-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0033_order_cost_alter_item_imageurl_alter_order_fulfiller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refunded',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
