# Generated by Django 6.0.5 on 2026-07-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0034_order_refunded'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Other', max_length=40),
        ),
    ]
