# Generated by Django 6.0.5 on 2026-07-21 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layered_site', '0036_project_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_print_reward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='print_reward_kg',
            field=models.IntegerField(default=0),
        ),
    ]
