from django.urls import path

from .views.admin import *
from .views.client import *

urlpatterns = [
    path("", index, name="index"),
    path("auth/login/", login_view, name="login"),
    path("auth/logout/", logout_view, name="logout"),
    path("oauth/callback/", auth_callback, name="auth_callback"),
    path("dashboard/", dashboard, name="dashboard"),
    path("projects/", projects, name="projects"),
    path("projects/<int:project_id>/", project_detail, name="project_detail"),
    path("projects/<int:project_id>/journal", create_journal, name="create_journal"),
    path("projects/<int:project_id>/edit/", edit_project, name="edit_project"),
    path("projects/<int:project_id>/editor-model/", update_editor_model, name="update_editor_model"),
    path("projects/<int:project_id>/delete/", delete_project, name="delete_project"),
    path("projects/<int:project_id>/lock/", lock_project, name="lock_project"),
    path("projects/<int:project_id>/unlock/", unlock_project, name="unlock_project"),
    path("projects/<int:project_id>/ship/", ship_project, name="ship_project"),
    path("explore/", explore, name="explore"),
    path("explore/<int:project_id>/", project_detail_explore, name="project_detail_explore"),
    path("shop/", shop, name="shop"),
    path("shop/<int:item_id>", item_detail, name="item_detail"),
    path("shop/<int:item_id>/order", order_item, name="order_item"),
    path("shop/<int:item_id>/delete/", delete_item, name="delete_item"),
    path("shop/<int:item_id>/edit/", edit_item, name="edit_item"),
    path("root/shop/create/", create_item, name="create_item"),
    path("projects/create/", create_project, name="create_project"),
    path("root/", admin_dash, name="admin_dash"),
    path("root/fulfillment/", fulfillment_dash, name="fulfillment_dash"),
    path("root/fulfillment/<int:order_id>/status/", update_order_status, name="update_order_status"),
    path("root/shop/", shop_dash, name="shop_dash"),
    path("root/review/", review_dash, name="review_dash"),
    path("root/review/<int:ship_id>", review_project, name="review_project"),
    path("root/review/<int:ship_id>/decision", t1_decision, name="t1_decision"),
    path("root/print/", print_dash, name="print_dash"),
    path("root/print/<int:ship_id>", print_project, name="print_project"),
    path("root/print/<int:ship_id>/claim", claim_print, name="claim_print"),
    path("root/print/<int:ship_id>/unclaim", unclaim_print, name="unclaim_print"),
    path("root/print/<int:ship_id>/decision", print_decision, name="print_decision"),
    path("root/ysws_review/", ysws_review_dash, name="ysws_review_dash"),
    path("root/ysws_review/<int:ship_id>", ysws_review_project, name="ysws_review_project"),
    path("root/ysws_review/<int:ship_id>/decision", t2_decision, name="t2_decision"),
    path("root/fraud_review/", fraud_review_dash, name="fraud_review_dash"),
    path("root/fraud_review/<int:ship_id>", fraud_review_project, name="fraud_review_project"),
    path("root/fraud_review/<int:ship_id>/decision", t3_decision, name="t3_decision"),
    path("root/audit_log/", audit_log, name="audit_log"),
    path("root/users", users, name="users"),
    path("root/users/edit/<int:user_id>", edit_user, name="edit_user"),
    path("root/projects/", manage_projects, name="manage_projects"),
    path("root/projects/edit/<int:project_id>/", admin_edit_project, name="admin_edit_project"),
    path("root/projects/delete/<int:project_id>/", db_delete_project, name="db_delete_project")
]